# Generated by Django 5.1 on 2024-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(max_length=256, unique=True),
        ),
    ]
